import type { User, Entity, RegulatoryDocument, GoverningBody, Director, Power } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "María González",
    email: "admin@morelos.gob.mx",
    password: "admin123",
    role: "Administrador",
  },
  {
    id: "2",
    name: "Carlos Ramírez",
    email: "editor@morelos.gob.mx",
    password: "editor123",
    role: "Editor",
  },
  {
    id: "3",
    name: "Ana Martínez",
    email: "lector@morelos.gob.mx",
    password: "lector123",
    role: "Lector",
  },
]

export const mockEntities: Entity[] = [
  {
    id: "1",
    folio: "SAyF-PF-REPOPA-IMIPE-OPD-2025-01",
    type: "Organismo",
    name: "Instituto Morelense de Información Pública y Estadística (IMIPE)",
    purpose: "Garantizar el derecho de acceso a la información pública y protección de datos personales",
    address: "Av. Morelos Sur No. 187, Colonia Las Palmas, Cuernavaca, Morelos",
    creationInstrument: "Decreto Gubernamental No. 234/2010",
    creationDate: "2010-03-15",
    officialPublication: 'Periódico Oficial "Tierra y Libertad" del 15 de marzo de 2010',
    observations: "Organismo autónomo con personalidad jurídica y patrimonio propios",
    status: "Activo",
    createdAt: "2024-01-10",
    requestLetter: "Oficio PFRA/001/2024",
    hasHistoricalRecords: true,
    historicalDocuments: ["antecedente_imipe_2009.pdf"],
  },
  {
    id: "2",
    folio: "SAyF-PF-REPOPA-DIF-OPD-2025-02",
    type: "Organismo",
    name: "Sistema DIF Morelos",
    purpose: "Promover la asistencia social y el bienestar de la población vulnerable",
    address: "Calle Matamoros No. 10, Centro, Cuernavaca, Morelos",
    creationInstrument: "Ley de Asistencia Social del Estado de Morelos",
    creationDate: "1986-12-01",
    officialPublication: "Periódico Oficial del 1 de diciembre de 1986",
    observations: "Institución de asistencia social con cobertura estatal",
    status: "Activo",
    createdAt: "2024-01-15",
    requestLetter: "Oficio PFRA/002/2024",
  },
  {
    id: "3",
    folio: "SAyF-PF-REPOPA-IEBEM-OPD-2025-03",
    type: "Organismo",
    name: "Instituto de la Educación Básica del Estado de Morelos (IEBEM)",
    purpose: "Administrar y coordinar los servicios de educación básica en el estado",
    address: "Av. Emiliano Zapata S/N, Col. Reforma, Cuernavaca, Morelos",
    creationInstrument: "Decreto de Creación IEBEM",
    creationDate: "1992-08-01",
    officialPublication: "Periódico Oficial del 1 de agosto de 1992",
    observations: "Organismo público descentralizado del sector educativo",
    status: "Activo",
    createdAt: "2024-02-01",
  },
  {
    id: "4",
    folio: "SAyF-PF-REPOPA-SSM-OPD-2025-04",
    type: "Organismo",
    name: "Servicios de Salud de Morelos (SSM)",
    purpose: "Prestar servicios de salud a la población del estado",
    address: "Calle Tabachines No. 8, Col. Acapantzingo, Cuernavaca, Morelos",
    creationInstrument: "Decreto de Creación de Servicios de Salud",
    creationDate: "1985-01-15",
    officialPublication: "Periódico Oficial del 15 de enero de 1985",
    observations: "Organismo descentralizado del sector salud",
    status: "Activo",
    createdAt: "2024-02-10",
  },
  {
    id: "5",
    folio: "SAyF-PF-REPOPA-FIDTUR-FI-2025-05",
    type: "Fideicomiso",
    name: "Fideicomiso para el Desarrollo Turístico de Morelos",
    purpose: "Promover y desarrollar la actividad turística en el estado",
    address: "Av. Morelos No. 187, Centro, Cuernavaca, Morelos",
    creationInstrument: "Contrato de Fideicomiso No. FID-2015-001",
    creationDate: "2015-09-10",
    officialPublication: "No requiere publicación oficial",
    observations: "Fideicomiso público con recursos estatales y federales",
    status: "Activo",
    createdAt: "2024-02-15",
    requestLetter: "Oficio PFRA/005/2024",
  },
  {
    id: "6",
    folio: "SAyF-PF-REPOPA-FIDINFRA-FI-2025-06",
    type: "Fideicomiso",
    name: "Fideicomiso para la Infraestructura Educativa de Morelos",
    purpose: "Administrar recursos para infraestructura educativa estatal",
    address: "Plaza de Armas S/N, Centro, Cuernavaca, Morelos",
    creationInstrument: "Contrato de Fideicomiso No. FID-2018-003",
    creationDate: "2018-05-20",
    officialPublication: "No aplica",
    observations: "Fideicomiso para construcción y mantenimiento de escuelas",
    status: "Activo",
    createdAt: "2024-03-01",
  },
  {
    id: "7",
    folio: "SAyF-PF-REPOPA-FIDCONV-FI-2025-07",
    type: "Fideicomiso",
    name: "Fideicomiso del Centro de Convenciones de Cuernavaca",
    purpose: "Administrar y operar el Centro de Convenciones",
    address: "Av. Emiliano Zapata 100, Col. Cantarranas, Cuernavaca",
    creationInstrument: "Contrato de Fideicomiso No. FID-2020-007",
    creationDate: "2020-11-10",
    officialPublication: "No aplica",
    observations: "Fideicomiso para promoción de eventos y congresos",
    status: "Activo",
    createdAt: "2024-03-15",
  },
  {
    id: "8",
    folio: "SAyF-PF-REPOPA-AEROCVA-EPEM-2025-08",
    type: "EPEM",
    name: "Aeropuerto de Cuernavaca",
    purpose: "Operar y administrar el aeropuerto civil del estado de Morelos",
    address: "Carretera Federal Cuernavaca-Cuautla Km 7.5, Temixco, Morelos",
    creationInstrument: "Decreto de Creación de Empresa de Participación Estatal",
    creationDate: "2005-07-15",
    officialPublication: "Periódico Oficial del 15 de julio de 2005",
    observations: "Empresa de participación estatal mayoritaria para servicios aeroportuarios",
    status: "Activo",
    createdAt: "2024-04-01",
    requestLetter: "Oficio PFRA/008/2024",
  },
]

export const mockRegulatoryDocs: RegulatoryDocument[] = [
  {
    id: "1",
    entityId: "1",
    type: "Reglamento Interior",
    issueDate: "2010-06-15",
    validity: "Vigente",
    file: "reglamento_imipe_2010.pdf",
    notes: "Última actualización en 2020",
  },
  {
    id: "2",
    entityId: "2",
    type: "Estatuto",
    issueDate: "2018-08-01",
    validity: "Vigente",
    file: "estatuto_cemr_2018.pdf",
    notes: "Revisión pendiente para 2025",
  },
]

export const mockGoverningBodies: GoverningBody[] = [
  {
    id: "1",
    entityId: "1",
    bodyType: "Consejo Directivo",
    memberName: "Lic. Roberto Hernández Pérez",
    position: "Presidente",
    appointmentDate: "2021-10-01",
    designationInstrument: "Acuerdo Gubernamental 345/2021",
    status: "Activo",
    observations: "Periodo de 3 años",
  },
  {
    id: "2",
    entityId: "1",
    bodyType: "Consejo Directivo",
    memberName: "Dra. Patricia López García",
    position: "Vocal",
    appointmentDate: "2021-10-01",
    designationInstrument: "Acuerdo Gubernamental 345/2021",
    status: "Activo",
    observations: "",
  },
]

export const mockDirectors: Director[] = [
  {
    id: "1",
    entityId: "1",
    name: "Lic. Juan Manuel Soto",
    position: "Director General",
    responsibilityType: "Dirección",
    startDate: "2022-01-15",
    supportDocument: "Nombramiento DG/2022/001",
  },
  {
    id: "2",
    entityId: "2",
    name: "Ing. María del Carmen Flores",
    position: "Directora Ejecutiva",
    responsibilityType: "Dirección",
    startDate: "2023-03-01",
    supportDocument: "Nombramiento DE/2023/005",
  },
]

export const mockPowers: Power[] = [
  {
    id: "1",
    entityId: "1",
    powerType: "Poder General para Actos de Administración",
    attorneys: ["Lic. Juan Manuel Soto"],
    grantDate: "2022-01-20",
    document: "poder_admin_001.pdf",
  },
  {
    id: "2",
    entityId: "2",
    powerType: "Poder Especial para Pleitos y Cobranzas",
    attorneys: ["Lic. María del Carmen Flores", "Lic. Roberto Hernández Pérez"],
    grantDate: "2023-03-15",
    document: "poder_pleitos_002.pdf",
  },
]
